### ISSUE TITLE
Container create setCmd() string[]

### ISSUE THREAD

**Issue by krzaczek** [docker-php/docker-php#151]
Hi,

I'm having problems creating a new container when passing array of string to `setCmd()` method

``` php
$containerConfig = new \Docker\API\Model\ContainerConfig();
$containerConfig->setName('test');
$containerConfig->setTty(true);
$containerConfig->setCmd(['ls', '-la']);
$manager->create($containerConfig);
```

This results in an `Internal Server Error`

``` php
#0 /Users/pawel/Documents/_Projekty/gitlab/printu/printu/vendor/php-http/plugins/src/ErrorPlugin.php(27): Http\Client\Plugin\ErrorPlugin->transformResponseToException(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /Users/pawel/Documents/_Projekty/gitlab/printu/printu/vendor/php-http/promise/src/FulfilledPromise.php(37): Http\Client\Plugin\ErrorPlugin->Http\Client\Plugin\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /Users/pawel/Documents/_Projekty/gitlab/printu/printu/vendor/php-http/plugins/src/ErrorPlugin.php(28): Http\Promise\FulfilledPromise->then(Object(Closure))
#3 /Users/pawel/Documents/_Projekty/gitlab/printu/printu/vendor/php-http/plugins/src/PluginClient.php(130): Http\Client\Plugin\ErrorPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#4 /Users/pawel/Documents/_Projekty/gitlab/printu/printu/vendor/php-http/plugins/src/PluginClient.php(144): Http\Client\Plugin\PluginClient->Http\Client\Plugin\{closure}(Object(GuzzleHttp\Psr7\Request))
#5 /Users/pawel/Documents/_Projekty/gitlab/printu/printu/vendor/php-http/plugins/src/PluginClient.php(84): Http\Client\Plugin\PluginClient->Http\Client\Plugin\{closure}(Object(GuzzleHttp\Psr7\Request))
#6 /Users/pawel/Documents/_Projekty/gitlab/printu/printu/vendor/stage1/docker-php/src/DockerClient.php(41): Http\Client\Plugin\PluginClient->sendRequest(Object(GuzzleHttp\Psr7\Request))
#7 /Users/pawel/Documents/_Projekty/gitlab/printu/printu/vendor/stage1/docker-php/generated/Resource/ContainerResource.php(72): Docker\DockerClient->sendRequest(Object(GuzzleHttp\Psr7\Request))
#8 /Users/pawel/Documents/_Projekty/gitlab/printu/printu/core/lib/Queue/Task/Project/Render.php(32): Docker\API\Resource\ContainerResource->create(Object(Docker\API\Model\ContainerConfig), Array)
#9 /Users/pawel/Documents/_Projekty/gitlab/printu/printu/core/lib/Queue/Jobs/Abstract.php(52): Queue_Task_Project_Render->fire(Object(Queue_Jobs_Beanstalkd), Array)
#10 /Users/pawel/Documents/_Projekty/gitlab/printu/printu/core/lib/Queue/Jobs/Beanstalkd.php(48): Queue_Jobs_Abstract->resolveAndFire(Array)
#11 /Users/pawel/Documents/_Projekty/gitlab/printu/printu/bin/queue/beanstalkd.php(76): Queue_Jobs_Beanstalkd->fire()
#12 {main}===========================================
```

And an docker error

```
time="2016-01-26T17:06:45.263342062+01:00" level=info msg="POST /containers/create?name=test" 
time="2016-01-26T17:06:45.295238709+01:00" level=error msg="Handler for POST /containers/create returned error: json: cannot unmarshal array into Go value of type string" 
time="2016-01-26T17:06:45.295299220+01:00" level=error msg="HTTP Error" err="json: cannot unmarshal array into Go value of type string" statusCode=500 
```

Am i missing something? Running dev-master of docker-php. Starting a container with `setCmd('string')` works ok.

**Comment by joelwurtz** [comment]
Seems strange as https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#create-a-container clearly state : 

> Cmd - Command to run specified as a string or an array of strings.

And our tests use the array syntax also : https://github.com/stage1/docker-php/blob/master/tests/Manager/ContainerManagerTest.php

What is your version of docker ?

**Comment by krzaczek** [comment]
```
root@web:~# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:06:12 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:06:12 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by joelwurtz** [comment]
:/ really weird, i cannot reproduce the same thing in local, 

can you give me a complete example that is failing for you i can run in my local env ? (There is no image in your example, and creation is wrong)

**Comment by krzaczek** [comment]
The $data array is something like this

```php
$data = [
    'container' => 'printu-renderer' // this is out image,
    'version' => 'latest',
    'job_id' => 'aJKAHDAKDHAKSJ',
    'project_id' => 12
]
```

Method `$oProject->getProductFamily()` returns a string so the `setCmd` params looks like this
`setCdm([10, '-rpcType', 'photobook'])`

Code execution
```php
        $docker = new Integrations_Docker();
        $containger = $docker->getContainerManager();

        $oProject = Project::factory($data['object_type']);

        $containerConfig = new \Docker\API\Model\ContainerConfig();
        $containerConfig->setImage(implode(':', [$data['container'], $data['version']]));
        $containerConfig->setTty(true);
        $containerConfig->setCmd([$data['project_id'], '-rpcType=', $oProject->getProductFamily()]);

        $hostConfig = new \Docker\API\Model\HostConfig();
        if (defined('DEVELOPMENT') && DEVELOPMENT) {
            $hostConfig->setExtraHosts(['printu.dev:10.10.0.80']);
        }
        $containerConfig->setHostConfig($hostConfig);

        $response = $containger->create(
            $containerConfig,
            ['name' => $data['container'] . "_" . $data['job_id']]
        );

        if (!$response) {
            $job->error();
        }

        $containger->start($response->getId());
```
class Integrations_Docker
```php
class Integrations_Docker
{
    /**
     * @var \Docker\Docker
     */
    protected $client;

    public function __construct()
    {
        //TODO [pawel] core_config
        $context = stream_context_create([
            'ssl' => [
                'cafile' => APP_PATH . '/data/docker/ca.pem',
                'local_cert' => APP_PATH . '/data/docker/cert.pem',
                'local_pk' => APP_PATH . '/data/docker/key.pem',
                'peer_name' => '10.10.0.1',
                'verify_peer_name' => true
            ],
        ]);

        $client = new \Docker\DockerClient([
            'remote_socket' => 'tcp://10.10.0.80:2376',
            'stream_context' => $context,
            'ssl' => true
        ]);

        $this->client = new \Docker\Docker($client);
    }

    /**
     * @return \Docker\Docker
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * @return \Docker\Manager\ContainerManager
     */
    public function getContainerManager()
    {
        return $this->client->getContainerManager();
    }

    public function getImageManager()
    {
        return $this->client->getImageManager();
    }
}
```

**Comment by krzaczek** [comment]
@joelwurtz I will try to reproduce this on a standard container like `debian:jessie` and so standard command like ['ls', '-la'] and will create a sample script for You to check it in Your env. Sine Im home now this will have to wait till tomorrow.

**Comment by joelwurtz** [comment]
Will wait then, thanks !

**Comment by krzaczek** [comment]
@joelwurtz ok I was able to replicate the problem. 

```php
$containerConfig->setCmd([$data['project_id'], '-rpcType=', $oProject->getProductFamily()]);
```

The error is caused by `$data['project_id']` because it's an `int` not `string`

**Comment by joelwurtz** [comment]
Ok, will maybe add type casting then in the generated code (should not be hard)

**Comment by joelwurtz** [comment]
Docker PHP, in 2.0, has now strict typing, so this kind of issues should not be possible anymore.
