### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by drsect0r** [docker-php/docker-php#158]
Improve the documentation to provide 100% functionality coverage.

**Comment by joelwurtz** [comment]
Good idea, PRs are welcome !

**Comment by drsect0r** [comment]
@joelwurtz I will try to do some work after I get a better understanding of it all. For now, could you provide an example how I can open container ports resulting in `0.0.0.0:32775->80/tcp`?

**Comment by joelwurtz** [comment]
ExposedPorts will only indicate that you expose a port on the container but it does nothing at docker level (it is used when linking containers for env variable and host alias)

If this is what you want, i think the right way would be to do the following : 

```php
$containerConfig = new ContainerConfig();
$exposedPorts = new \ArrayObject();
$exposedPorts['80/tcp'] = new \stdClass();
$containerConfig->setExposedPorts($exposedPorts);
```

I don't have any informations on the object needed by the key as even the docker documentation tell us nothing (see https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#create-a-container). Need to dig into the source code of docker to know what config / options are available...

However if you want to do host port mapping (and not only exposition inside container), you should use the `setPortsBindings` method on the `HostConfig` object for the container config

```php
$containerConfig = new ContainerConfig();
$hostConfig = new HostConfig();
$mapPorts = new \ArrayObject();

$hostPortBinding = new PortBinding();
$hostPortBinding->setHostPort('32775');
$hostPortBinding->setHostIp('0.0.0.0');

$mapPorts['80/tcp'] = $hostPortBinding;
$hostConfig->setPortBindings($mapPorts);
$containerConfig->setHostConfig($hostConfig);
```

**Comment by joelwurtz** [comment]
A good step for documentation would be first to add a description on each field in the swagger schema.

**Comment by drsect0r** [comment]
@joelwurtz Thank you for your help so far, I appreciate it.

I still encounter an exception; my resulting ContainerConfig object is as follows: 

The stack trace doesn't mention a lot.
``` php 
...
"trace": [
      {
        "file": "/con/data/http/root/vendor/php-http/plugins/src/ErrorPlugin.php",
        "line": 27,
        "function": "transformResponseToException",
        "class": "Http\Client\Plugin\ErrorPlugin",
        "type": "->",
        "args": [
          {},
          {}
        ]
      },
      {
        "file": "/con/data/http/root/vendor/php-http/promise/src/FulfilledPromise.php",
        "line": 35,
        "function": "Http\Client\Plugin\{closure}",
        "class": "Http\Client\Plugin\ErrorPlugin",
        "type": "->",
        "args": [
          {}
        ]
      },
      {
        "file": "/con/data/http/root/vendor/php-http/plugins/src/ErrorPlugin.php",
        "line": 28,
        "function": "then",
        "class": "Http\Promise\FulfilledPromise",
        "type": "->",
        "args": [
          {}
        ]
      },
      {
        "file": "/con/data/http/root/vendor/php-http/plugins/src/PluginClient.php",
        "line": 133,
        "function": "handleRequest",
        "class": "Http\Client\Plugin\ErrorPlugin",
        "type": "->",
        "args": [
          {},
          {},
          {}
        ]
      },
      {
        "file": "/con/data/http/root/vendor/php-http/plugins/src/PluginClient.php",
        "line": 147,
        "function": "Http\Client\Plugin\{closure}",
        "class": "Http\Client\Plugin\PluginClient",
        "type": "->",
        "args": [
          {}
        ]
      },
      {
        "file": "/con/data/http/root/vendor/php-http/plugins/src/PluginClient.php",
        "line": 87,
        "function": "Http\Client\Plugin\{closure}",
        "class": "Http\Client\Plugin\PluginClient",
        "type": "->",
        "args": [
          {}
        ]
      },
      {
        "file": "/con/data/http/root/vendor/docker-php/docker-php/src/DockerClient.php",
        "line": 41,
        "function": "sendRequest",
        "class": "Http\Client\Plugin\PluginClient",
        "type": "->",
        "args": [
          {}
        ]
      },
      {
        "file": "/con/data/http/root/vendor/docker-php/docker-php/generated/Resource/ContainerResource.php",
        "line": 76,
        "function": "sendRequest",
        "class": "Docker\DockerClient",
        "type": "->",
        "args": [
          {}
        ]
      },
...
```
``` php
Docker\API\Model\ContainerConfig Object
(
    [id:protected] => 
    [names:protected] => 
    [image:protected] => drsect0r/server/nginx:1.0
    [command:protected] => 
    [created:protected] => 
    [status:protected] => 
    [ports:protected] => 
    [labels:protected] => 
    [sizeRw:protected] => 
    [sizeRootFs:protected] => 
    [hostname:protected] => 
    [domainname:protected] => 
    [user:protected] => 
    [attachStdin:protected] => 
    [attachStdout:protected] => 
    [attachStderr:protected] => 
    [tty:protected] => 
    [openStdin:protected] => 
    [stdinOnce:protected] => 
    [env:protected] => 
    [cmd:protected] => 
    [entrypoint:protected] => 
    [mounts:protected] => 
    [workingDir:protected] => 
    [networkDisabled:protected] => 
    [macAddress:protected] => 
    [exposedPorts:protected] => 
    [networkSettings:protected] => 
    [hostConfig:protected] => Docker\API\Model\HostConfig Object
        (
            [binds:protected] => 
            [links:protected] => Array
                (
                    [0] => drsect0r.server.php-fpm.f529272d
                )

            [lxcConf:protected] => 
            [memory:protected] => 
            [memorySwap:protected] => 
            [cpuShares:protected] => 
            [cpuPeriod:protected] => 
            [cpusetCpus:protected] => 
            [cpusetMems:protected] => 
            [blkioWeight:protected] => 
            [blkioWeightDevice:protected] => 
            [blkioDeviceReadBps:protected] => 
            [blkioDeviceReadIOps:protected] => 
            [blkioDeviceWriteBps:protected] => 
            [blkioDeviceWriteIOps:protected] => 
            [memorySwappiness:protected] => 
            [oomKillDisable:protected] => 
            [portBindings:protected] => ArrayObject Object
                (
                    [storage:ArrayObject:private] => Array
                        (
                            [80/tcp] => Docker\API\Model\PortBinding Object
                                (
                                    [hostPort:protected] => 1004
                                    [hostIp:protected] => 0.0.0.0
                                )

                        )

                )

            [publishAllPorts:protected] => 
            [privileged:protected] => 
            [readonlyRootfs:protected] => 
            [dns:protected] => 
            [dnsSearch:protected] => 
            [extraHosts:protected] => 
            [volumesFrom:protected] => Array
                (
                    [0] => drsect0r.data.files.f529272d
                )

            [capAdd:protected] => 
            [capDrop:protected] => 
            [restartPolicy:protected] => 
            [networkMode:protected] => 
            [devices:protected] => 
            [ulimits:protected] => 
            [securityOpt:protected] => 
            [logConfig:protected] => 
            [cgroupParent:protected] => 
        )

)

```

**Comment by joelwurtz** [comment]
The exception should have a Reponse Object which contains the reason of the failure, can you show it ?

Also you can activate / view logs on your docker server to see the errors on the api

**Comment by drsect0r** [comment]
```
[2016-02-09 14:56:47] lumen.ERROR: Http\Client\Plugin\Exception\ServerErrorException: Internal Server Error in /con/data/http/root/vendor/php-http/plugins/src/ErrorPlugin.php:49
Stack trace:
#0 /con/data/http/root/vendor/php-http/plugins/src/ErrorPlugin.php(27): Http\Client\Plugin\ErrorPlugin->transformResponseToException(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /con/data/http/root/vendor/php-http/promise/src/FulfilledPromise.php(35): Http\Client\Plugin\ErrorPlugin->Http\Client\Plugin\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /con/data/http/root/vendor/php-http/plugins/src/ErrorPlugin.php(28): Http\Promise\FulfilledPromise->then(Object(Closure))
#3 /con/data/http/root/vendor/php-http/plugins/src/PluginClient.php(133): Http\Client\Plugin\ErrorPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#4 /con/data/http/root/vendor/php-http/plugins/src/PluginClient.php(147): Http\Client\Plugin\PluginClient->Http\Client\Plugin\{closure}(Object(GuzzleHttp\Psr7\Request))
#5 /con/data/http/root/vendor/php-http/plugins/src/PluginClient.php(87): Http\Client\Plugin\PluginClient->Http\Client\Plugin\{closure}(Object(GuzzleHttp\Psr7\Request))
#6 /con/data/http/root/vendor/docker-php/docker-php/src/DockerClient.php(41): Http\Client\Plugin\PluginClient->sendRequest(Object(GuzzleHttp\Psr7\Request))
#7 /con/data/http/root/vendor/docker-php/docker-php/generated/Resource/ContainerResource.php(76): Docker\DockerClient->sendRequest(Object(GuzzleHttp\Psr7\Request))
#8 /con/data/http/root/app/Http/Controllers/Docker/DeployerController.php(149): Docker\API\Resource\ContainerResource->create(Object(Docker\API\Model\ContainerConfig))
#9 [internal function]: App\Http\Controllers\Docker\DeployerController->index(Object(Illuminate\Http\Request))
#10 /con/data/http/root/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#11 /con/data/http/root/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(577): Illuminate\Container\Container->call(Array, Array)
#12 /con/data/http/root/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(543): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#13 /con/data/http/root/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(517): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\Docker\DeployerController), 'index', Array)
#14 /con/data/http/root/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(485): Laravel\Lumen\Application->callControllerAction(Array)
#15 /con/data/http/root/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(470): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#16 /con/data/http/root/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(372): Laravel\Lumen\Application->handleFoundRoute(Array)
#17 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#18 /con/data/http/root/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /con/data/http/root/app/Http/Middleware/ProcessJsonMiddleware.php(30): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: App\Http\Middleware\ProcessJsonMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /con/data/http/root/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /con/data/http/root/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /con/data/http/root/vendor/illuminate/pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /con/data/http/root/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(617): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /con/data/http/root/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(378): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#28 /con/data/http/root/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(323): Laravel\Lumen\Application->dispatch(NULL)
#29 /con/data/http/root/public/index.php(28): Laravel\Lumen\Application->run()
#30 {main}  ```

**Comment by joelwurtz** [comment]
More the content of $exception->getReponse()->getBody()->getContents() :)

**Comment by joelwurtz** [comment]
And if there is nothing it should be on the docker side

**Comment by drsect0r** [comment]
You beat me to it! cannot unmarshal object into Go value of type []nat.PortBinding

**Comment by drsect0r** [comment]
@joelwurtz Maybe this is related: https://github.com/ErlNETS/nkdocker/issues/4?

**Comment by joelwurtz** [comment]
Hum, yes this code 

```php
$hostPortBinding = new PortBinding();
$hostPortBinding->setHostPort('32775');
$hostPortBinding->setHostIp('0.0.0.0');

$mapPorts['80/tcp'] = $hostPortBinding;
```

Should be transformed to 

```
$hostPortBinding = new PortBinding();
$hostPortBinding->setHostPort('32775');
$hostPortBinding->setHostIp('0.0.0.0');

$mapPorts['80/tcp'] = [$hostPortBinding];
```

But there is certainly an error this lib, will do an update tonight

**Comment by drsect0r** [comment]
@joelwurtz Thanks!, that did it! :+1:

**Comment by joelwurtz** [comment]
Closing this as this issue is rather old.
