### ISSUE TITLE
Uncaught Http\Client\Plugin\Exception\ServerErrorException: Internal Server Error

### ISSUE THREAD

**Issue by howardshaw** [docker-php/docker-php#171]
Use composer to install docker-php 1.22.0  as below
```shell
composer require docker-php
```

test to create a container but encount below error
```shell
$ php test.php
PHP Fatal error:  Uncaught Http\Client\Plugin\Exception\ServerErrorException: Internal Server Error in /home/vagrant/Code/testdir/vendor/php-http/plugins/src/ErrorPlugin.php:49
Stack trace:
#0 /home/vagrant/Code/testdir/vendor/php-http/plugins/src/ErrorPlugin.php(27): Http\Client\Plugin\ErrorPlugin->transformResponseToException(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/vagrant/Code/testdir/vendor/php-http/promise/src/FulfilledPromise.php(35): Http\Client\Plugin\ErrorPlugin->Http\Client\Plugin\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/vagrant/Code/testdir/vendor/php-http/plugins/src/ErrorPlugin.php(28): Http\Promise\FulfilledPromise->then(Object(Closure))
#3 /home/vagrant/Code/testdir/vendor/php-http/plugins/src/PluginClient.php(133): Http\Client\Plugin\ErrorPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#4 /home/vagrant/Code/testdir/vendor/php-http/plugins/src/PluginClient.php(147): Http\Client\Plugin\PluginClient->Http\Client\Plugin\{closur in /home/vagrant/Code/testdir/vendor/php-http/plugins/src/ErrorPlugin.php on line 49

Fatal error: Uncaught Http\Client\Plugin\Exception\ServerErrorException: Internal Server Error in /home/vagrant/Code/testdir/vendor/php-http/plugins/src/ErrorPlugin.php:49
Stack trace:
#0 /home/vagrant/Code/testdir/vendor/php-http/plugins/src/ErrorPlugin.php(27): Http\Client\Plugin\ErrorPlugin->transformResponseToException(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/vagrant/Code/testdir/vendor/php-http/promise/src/FulfilledPromise.php(35): Http\Client\Plugin\ErrorPlugin->Http\Client\Plugin\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/vagrant/Code/testdir/vendor/php-http/plugins/src/ErrorPlugin.php(28): Http\Promise\FulfilledPromise->then(Object(Closure))
#3 /home/vagrant/Code/testdir/vendor/php-http/plugins/src/PluginClient.php(133): Http\Client\Plugin\ErrorPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#4 /home/vagrant/Code/testdir/vendor/php-http/plugins/src/PluginClient.php(147): Http\Client\Plugin\PluginClient->Http\Client\Plugin\{closur in /home/vagrant/Code/testdir/vendor/php-http/plugins/src/ErrorPlugin.php on line 49

```

code as bellow
```php

<?php
//test.php
require __DIR__ . '/vendor/autoload.php';

$client = new Docker\DockerClient([
    'remote_socket' => 'tcp://192.168.33.10:2375',
    'ssl' => false,
]);
$docker = new Docker\Docker($client);


$containerManager = $docker->getContainerManager();

$containerConfig = new Docker\API\Model\ContainerConfig();
$containerConfig->setImage('busybox:latest');
$containerConfig->setCmd(['echo', 'I am running a command']);

$containerCreateResult = $containerManager->create($containerConfig);

```

the connection to docker daemon is ok.

```shell
$ telnet 192.168.33.10 2375
Trying 192.168.33.10...
Connected to 192.168.33.10.
Escape character is '^]'.

HTTP/1.1 400 Bad Request

Connection closed by foreign host.
$ curl http://192.168.33.10:2375/_ping
OK

```

**Comment by joelwurtz** [comment]
Exception should have a Response object, can you try to show the content of this Response Object (it should contain the error on docker side ) ?

```php
try {
    $containerCreateResult = $containerManager->create($containerConfig);
} catch(Http\Client\Plugin\Exception\ServerErrorException $exception) {
     echo $exception->getResponse()->getBody()->getContents();
}
```

**Comment by howardshaw** [comment]
@joelwurtz  thank you so much.
I tried uninstall and reinstall docker-engine,the problem gone.
I think there is something wront with docker daemon,not related to docker-php.Pls close it

**Comment by joelwurtz** [comment]
Thanks for the feedback
