### ISSUE TITLE
Error on build image by ContextBuilder

### ISSUE THREAD

**Issue by ScaryDonetskiy** [docker-php/docker-php#258]
## Environment

- OS: Ubuntu 16.04
- PHP version: 7.1.10
- Docker version: 17.09.0-ce
- Library version: 1.24

## Description of bug 
When I try to build image by ContextBuilder I get an error about Invalid resource type

```php
$docker = new \Docker\Docker();
$contextBuilder = new \Docker\Context\ContextBuilder();
$contextBuilder->from('ubuntu:latest');
$contextBuilder->run('apt-get update');
$docker->getImageManager()->build($contextBuilder->getContext()->toStream());
```
```
PHP Fatal error:  Uncaught InvalidArgumentException: Invalid resource type: unknown type in /var/www/dockent/vendor/guzzlehttp/psr7/src/functions.php:116
Stack trace:
#0 /var/www/dockent/vendor/guzzlehttp/psr7/src/Request.php(53): GuzzleHttp\Psr7\stream_for(Resource id #185)
#1 /var/www/dockent/vendor/php-http/message/src/MessageFactory/GuzzleMessageFactory.php(31): GuzzleHttp\Psr7\Request->__construct('POST', Object(GuzzleHttp\Psr7\Uri), Array, Resource id #185, '1.1')
#2 /var/www/dockent/vendor/docker-php/docker-php/generated/Resource/ImageResource.php(102): Http\Message\MessageFactory\GuzzleMessageFactory->createRequest('POST', '/build?q=0&noca...', Array, Resource id #185)
#3 /var/www/dockent/vendor/docker-php/docker-php/src/Manager/ImageManager.php(35): Docker\API\Resource\ImageResource->build(Resource id #185, Array, 'object')
#4 /var/www/dockent/test.php(47): Docker\Manager\ImageManager->build(Resource id #185)
#5 {main}
  thrown in /var/www/dockent/vendor/guzzlehttp/psr7/src/functions.php on line 116

```

_If you need more information - write it in the comments_

**Comment by joelwurtz** [comment]
This should be good in 2.0
