### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by jaschaio** [docker-php/docker-php#305]
I have the same issue as #239, but I have no typo within my docker.sock volume mount.

This is the error:
```
Fatal error: Uncaught Http\Client\Socket\Exception\ConnectionException: Permission denied in /var/www/html/vendor/php-http/socket-client/src/Client.php:114 Stack trace: #0 /var/www/html/vendor/php-http/socket-client/src/Client.php(82): Http\Client\Socket\Client->createSocket(Object(GuzzleHttp\Psr7\Request), 'unix:///docker....', false) #1 /var/www/html/vendor/php-http/client-common/src/HttpClientDecorator.php(27): Http\Client\Socket\Client->sendRequest(Object(GuzzleHttp\Psr7\Request)) #2 /var/www/html/vendor/php-http/client-common/src/PluginClient.php(81): Http\Client\Common\EmulatedHttpAsyncClient->sendRequest(Object(GuzzleHttp\Psr7\Request)) #3 /var/www/html/vendor/php-http/client-common/src/Plugin/AddHostPlugin.php(64): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request)) #4 /var/www/html/vendor/php-http/client-common/src/PluginClient.php(160): Http\Client\Common\Plugin\AddHostPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure)) #5 /var/www/h in /var/www/html/vendor/php-http/socket-client/src/Client.php on line 114
```

This is the output from `cat /etc/group | grep docker` on the host:
```
docker:x:999:nginx
```

This is the output from `cat /etc/group | grep docker` inside the container where I am running docker-php together with nginx:
```
docker:x:999:nginx
```

I have mounted the socket like this:
```
volumes:
            - /var/run/docker.sock:/docker.sock
```

And I am trying to get a container list like this:
```
use Docker\Docker;
use Docker\DockerClientFactory;

$client = DockerClientFactory::create([
    'remote_socket' => 'unix:///docker.sock'
]);
$docker = Docker::create($client);

$containers = $docker->containerList();

foreach ($containers as $container) {
    var_dump($container->getNames());
}
```

If I try to curl the socket from within the container with `curl --unix-socket /docker.sock http://localhost/containers/json` it works.

**Comment by guillemcanal** [comment]
Hi @jaschaio ,the Docker socket can only be used by the `root` user, unless you decide to change the access permissions using `chmod` which is not recommended. For any use case involving a web server (such as nginx + php-fpm), you may want to create a tcp proxy to the docker socket (not exposed to the web), using `socat` (not ideal), `haproxy` or something fancier like https://github.com/buildkite/sockguard

**Comment by dbjpanda** [comment]
Getting same issue Permission denied in /var/www/html/vendor/php-http/socket-client/src/Client.php:114
